model:
  backbone: 'resnet50'
  embedding_dim: 512  # Changed from feat_dim
  input_size: 224
  attention_type: 'cbam'  # Added for attention mechanism
  dropout: 0.1
  pretrained: true  # Added for backbone loading

training:
  batch_size: 32
  epochs: 20
  warmup_epochs: 2
  freeze_backbone_epochs: 1
  
  # Optimizer config structure
  optimizer:
    type: 'adam'  # Changed from 'adamw' to match trainer expectations
    lr: 3e-4
    weight_decay: 1e-4
  
  # Scheduler config structure  
  scheduler:
    type: 'cosine'
    min_lr: 1e-6
  
  # Loss configuration structure
  loss:
    type: 'combined'
    margin: 1.0
    twin_weight: 2.0
    same_weight: 1.0
    other_weight: 1.0
  
  # Mining strategy
  hard_twin_ratio: 0.5
  other_ratio: 0.25

data:
  dataset_path: 'dataset'
  pairs_json_path: 'dataset/pairs.json'  # Added pairs.json path
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  num_workers: 4
  pin_memory: true
  
  # Augmentation
  input_size: 224  # Moved from model section for consistency
  color_jitter: 0.4
  cutmix_alpha: 1.0
  cutmix_prob: 0.5
  horizontal_flip: false  # Important: NO flipping for twins

# Renamed from optimization to match trainer expectations
mixed_precision: true
gradient_checkpointing: true
gradient_clip: 1.0

logging:
  log_interval: 100
  save_interval: 1000
  checkpoint_dir: 'checkpoints'
  log_dir: 'logs'
  use_wandb: false
  wandb_project: 'twin-face-verification'

inference:
  high_res_size: 640
  top_k_rerank: 10
  distance_metric: 'cosine'  # 'cosine' or 'l2'
